language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
env:
    - NUMPY_VER=1.11
install:
    - pip install --upgrade pip
    - pip install -q numpy==$NUMPY_VER
    - pip install .
script: python -m unittest -v
notifications:
    email: false
